spring.application.name=auth-service
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/careconnect_auth
spring.datasource.username=root
spring.datasource.password=your_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret=u0apnJQZKWzgmaE9mJrnvDIqalNgtNycXCrzd9ioPgREpWxIwHSFSRMDM2ECxa2sjlvdzLo7MzmJnk9Fk2ahqw==
jwt.expiration=86400000
