export { api } from './axios';
export { TOKEN_KEY } from '@/store/authStorage';
export * from './auth.api';
export * from './admin.api';
export * from './patient.api';
export * from './receptionist.api';
export * from './appointment.api';
export * from './clinical.api';
export * from './billing.api';
export * from './lab.api';
export * from './notifications.api';
