spring.application.name=clinical-service
server.port=8084

spring.datasource.url=jdbc:mysql://localhost:3306/careconnect_clinical
spring.datasource.username=root
spring.datasource.password=ROOT
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

jwt.secret=u0apnJQZKWzgmaE9mJrnvDIqalNgtNycXCrzd9ioPgREpWxIwHSFSRMDM2ECxa2sjlvdzLo7MzmJnk9Fk2ahqw==

auth.service.url=http://localhost:8081
patient.service.url=http://localhost:8082
appointment.service.url=http://localhost:8083
